apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-mesh-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "istio-addons.name" . }}
    chart: {{ template "istio-addons.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    prometheus-monitoring: "true"
    monitoring: istio-mesh
spec:
  jobLabel: istio-mesh
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [mixer]}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: prometheus
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-component-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "istio-addons.name" . }}
    chart: {{ template "istio-addons.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    prometheus-monitoring: "true"
    monitoring: istio-components
spec:
  jobLabel: istio-components
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [mixer,pilot,galley,citadel]}
  namespaceSelector:
    any: true
  endpoints:
  - port: http-monitoring
    interval: 15s
  - port: http-policy-monitoring
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-stats-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "istio-addons.name" . }}
    chart: {{ template "istio-addons.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    prometheus-monitoring: "true"
    monitoring: istio-proxies
spec:
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats
  endpoints:
  - path: /stats/prometheus
    targetPort: {{ .Values.istioProxyPrometheusPort }}
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
    - action: labelmap
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
