repositories:
  - name: istio.io
    url: https://storage.googleapis.com/istio-release/releases/1.3.4/charts/
  - name: stable
    url: http://mirror.azure.cn/kubernetes/charts/

helmDefaults:
  wait: true
  timeout: 600

releases:
#  - name: istio-init
#    namespace: system-istio
#    chart: istio.io/istio-init
#    version: 1.3.4
#  - name: istio
#    namespace: system-istio
#    chart: istio.io/istio
#    version: 1.3.4
#    needs:
#      - system-istio/istio-init
#    values:
#      - istio-values.yaml

#  - name: prometheus-operator
#    namespace: system-monitoring
#    chart: stable/prometheus-operator
#    version: 6.21.0
#    values:
#      - prometheus-values.yaml

#  - name: system-addons
#    namespace: system-monitoring
#    chart: ./helmchart.d/system-addons
#    version: 0.0.1

#  - name: istio-addons
#    namespace: system-istio
#    chart: ./helmchart.d/istio-addons
#    version: 0.0.1
#    needs:
#      - system-istio/istio
#      - system-monitoring/prometheus-operator
#
#  - name: mysql
#    namespace: petclinic
#    chart: stable/mysql
#    version: 1.4.0
#    values:
#      - mysql-values.yaml
#
#  - name: petclinic-customers-service
#    namespace: petclinic
#    chart: ./helmchart.d/spring-boot
#    version: 0.0.1
#    needs:
#      - petclinic/mysql
#    values:
#      - petclinic-customers-service-values.yaml
#  - name: petclinic-vets-service
#    namespace: petclinic
#    chart: ./helmchart.d/spring-boot
#    version: 0.0.1
#    needs:
#      - petclinic/mysql
#    values:
#      - petclinic-vets-service-values.yaml
#  - name: petclinic-visits-service
#    namespace: petclinic
#    chart: ./helmchart.d/spring-boot
#    version: 0.0.1
#    needs:
#      - petclinic/mysql
#    values:
#      - petclinic-visits-service-values.yaml

  - name: spring-petclinic-ui
    namespace: petclinic
    chart: ./helmchart.d/spring-petclinic-ui
    version: 0.0.1
